name: dependency-updates
on:
  branch_protection_rule:
  check_run:
  check_suite:
  delete:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  repository_dispatch:
  status:
  watch:
  push:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  darkreader-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: update darkreader
        id: update
        run: curl -L https://cdn.jsdelivr.net/npm/darkreader -o darkreader.js
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          signoff: true
          delete-branch: true
          commit-message: update darkreader
          branch: update-darkreader
          title: update darkreader
          body: update darkreader
