name: HTML Validator

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  html5validator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: /github/workspace
        log_level: INFO
        css: true
        skip_git_check: true
      continue-on-error: true
    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.log
