name: markdown-render

on:
  push:
    paths:
      - .github/workflows/markdown-render.yml
      - files/Stundenplan.md
  workflow_dispatch:

jobs:
  repo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         ref: ${{ github.ref_name }}
        
      - name: update repos
        run: | 
         rm -rf files/Stundenplan.html
         echo -e "<meta charset="utf-8">\n$(curl -X POST https://api.github.com/markdown/raw --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header "Content-Type: text/plain" -d "$(cat files/Stundenplan.md)")" | tee files/Stundenplan.html
